name: publish image

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - "go.mod"
      - "go.sum"
      - 'Dockerfile'
      - '.github/workflows/publish-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - "go.mod"
      - "go.sum"
      - 'Dockerfile'
      - '.github/workflows/publish-image.yml'
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: version
        uses: haya14busa/action-cond@v1
        with:
          cond: ${{ github.event_name == 'release' }}
          if_true: ${{ github.event.release.tag_name }}
          if_false: "canary"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta GitHub
        id: meta-github
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}"
          tags: |
            type=raw,value=${{ steps.version.outputs.value }}
            type=raw,value={{sha}}
            type=ref,event=branch
          flavor: |
            latest=true

      - name: Set up  QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get date
        id: date
        run: echo "value=$(date +%FT%TZ)" >> "${GITHUB_OUTPUT}"

      - name: Build/Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta-github.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta-github.outputs.tags }}
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
            SOURCE_COMMIT=${{ github.sha }}
            SOURCE_BRANCH=${{ github.ref }}
            BUILD_DATE=${{ steps.date.outputs.value }}
            BUILD_USER=github-actions
